export const CLICK_BUTTON = "CLICK_BUTTON";
export const GET_TOP_TEN = "GET_TOP_TEN";
export const ADD_EARTHQUAKE = "ADD_EARTHQUAKE";
export const GET_EARTHQUAKE_DETAILS = "GET_EARTHQUAKE_DETAILS";
export const RETRIEVE_LATEST = "RETRIEVE_LATEST";
